# Generated by Django 2.2.3 on 2019-08-14 04:56

from django.db import migrations, models
import guests.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_party_rehearsal_dinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='save_the_date_id',
            field=models.CharField(db_index=True, default=guests.models._random_uuid, max_length=32, unique=True),
        ),
    ]
