# Generated by Django 2.2.3 on 2019-08-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20190814_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
