# Generated by Django 2.2.3 on 2019-08-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_auto_20190814_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(blank=True, choices=[('formal', 'formal'), ('fun', 'fun'), ('dimagi', 'dimagi')], max_length=10, null=True),
        ),
    ]
