# Generated by Django 2.2.3 on 2019-09-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_auto_20190815_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='responded_to_invitation',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
