# Generated by Django 2.2.3 on 2019-10-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_party_responded_to_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='follow_up_opened',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='follow_up_sent',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
