# Generated by Django 2.2.4 on 2019-12-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0021_auto_20191020_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='reminder_sent',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
